version: '3.3'

services:
  age_sharding0:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: age_sharding0
    restart: always
    environment:
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: stud
      MYSQL_DATABASE: Age
    ports:
      - 3330:3306

  age_sharding1:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: age_sharding1
    restart: always
    environment:
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: stud
      MYSQL_DATABASE: Age
    ports:
      - 3331:3306

  age_sharding2:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: age_sharding2
    restart: always
    environment:
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: stud
      MYSQL_DATABASE: Age
    ports:
      - 3332:3306
  
  age_sharding3:
    build:
      context: mysql
      dockerfile: Dockerfile
    container_name: age_sharding3
    restart: always
    environment:
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
      MYSQL_ROOT_PASSWORD: stud
      MYSQL_DATABASE: Age
    ports:
      - 3333:3306
  
  proxysql:
    build:
      context: proxysql
      dockerfile: Dockerfile
    container_name: proxysql
    depends_on:
      - "age_sharding0"
      - "age_sharding1"
      - "age_sharding2"
      - "age_sharding3"
    ports:
      - "8085:8085"
